### ISSUE TITLE
Extension fails to load after upgrade to v0.6.0

### ISSUE THREAD

**Issue by cmuhire** [elixir-lsp/elixir-ls#371]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.10.3, Erlang/OTP 22 
* Operating system: Linux (Ubuntu 16.04)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS v0.6.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

---

### Description

The extension fails to properly load after upgrading to v0.6.0. Syntax highlighting works but other features like autocompletion, navigation, deps fetching and PLT build do not work and the extension does not appear in the dropdown under `View > Output`.

A `Cannot find module 'shelljs'` error is printed in the DevTools console.
![elixir_ls](https://user-images.githubusercontent.com/6691440/95008455-4d41b400-061a-11eb-8017-9567be2c3624.png)

![elixir_ls](https://user-images.githubusercontent.com/6691440/95008458-55015880-061a-11eb-8774-47d65284ec5e.gif)

**Comment by cmuhire** [comment]
I realized the issue is probably on the JS side so I'm closing this issue in favour of the one I opened on the VS Code package repo https://github.com/elixir-lsp/vscode-elixir-ls/issues/145
