### ISSUE TITLE
ElixirLS will not compile with Elixir 1.14

### ISSUE THREAD

**Issue by jstr** [elixir-lsp/elixir-ls#1250]
ElixirLS will not compile with Elixir 1.14, although the support matrix and `mix.exs` file suggest 1.14 is supported (regardless of version support policy).

The compilation failure is:

```
==> language_server
Compiling 580 files (.ex)

== Compilation error in file lib/language_server/mix_tasks/format.ex ==
** (CompileError) lib/language_server/mix_tasks/format.ex:745: cannot use ^size outside of match clauses
    (elixir 1.14.5) src/elixir_bitstring.erl:254: :elixir_bitstring.expand_spec_arg/4
    (elixir 1.14.5) src/elixir_bitstring.erl:190: :elixir_bitstring.expand_each_spec/6
    (elixir 1.14.5) src/elixir_bitstring.erl:160: :elixir_bitstring.expand_specs/7
    (elixir 1.14.5) src/elixir_bitstring.erl:38: :elixir_bitstring.expand/8
    (elixir 1.14.5) src/elixir_bitstring.erl:14: :elixir_bitstring.expand/5
```

The language server implementation seems to use Elixir 1.15 specific bitstring matching syntax.

Support matrix and mix file should probably require 1.15.
