### ISSUE TITLE
compile_env error seems wrong

### ISSUE THREAD

**Issue by AHBruns** [elixir-lsp/elixir-ls#1008]
### Precheck

* Do a quick search and make sure the issue has not yet been reported
* Do not use the issues tracker for guidance, questions or support (try Elixir Forum, Stack Overflow, Slack, etc. instead)
* If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?

### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.15.5 (compiled with Erlang/OTP 26)
* Elixir Language Server version: 
how can I determine this?
* Operating system: 
Mac
* Editor or IDE name (e.g. Emacs/VSCode): 
VSCode
* Editor Plugin/LSP Client name and version:
ElixirLS: Elixir support and debugger v0.17.1

### Current behavior

I have a module:

```elixir
defmodule Grimoire.Bridges.HubspotClient do
  @base_url Application.compile_env!(:grimoire, [Grimoire.Bridges.Hubspot, :base_url])
```

I get this error:

```
(ArgumentError) could not fetch application environment [Grimoire.Bridges.Hubspot, :base_url] for application :grimoire because the application was not loaded nor configured

Stacktrace:
  │ (elixir 1.15.5) lib/application.ex:635: Application.compile_env!/3
  │ lib/grimoire/bridges/hubspot/hubspot_client.ex:10: (module)Elixir
```

here's the corresponding ElixirLS log:

```
[Warn  - 3:45:28 AM] 
== Compilation error in file lib/grimoire/bridges/hubspot/hubspot_client.ex ==
** (ArgumentError) could not fetch application environment [Grimoire.Bridges.Hubspot, :base_url] for application :grimoire because the application was not loaded nor configured
    (elixir 1.15.5) lib/application.ex:635: Application.compile_env!/3
    lib/grimoire/bridges/hubspot/hubspot_client.ex:10: (module)
```

The issue is that, the error does seem to be accurate. I can compile my application without any warnings, or issues. Just to confirm, this is in my application's config.exs file:

```elixir
config :grimoire, Grimoire.Bridges.Hubspot,
  base_url: "****",
```

### Expected behavior

No error

**Comment by lukaszsamson** [comment]
Please create a small repro and fill the error template

**Comment by lukaszsamson** [comment]
I reproduced it. Most likely the problem was introduced in https://github.com/elixir-lsp/elixir-ls/commit/d9cc23a45b049f41149ee874a36a19820dbc8a94. I need to look for another workaround for https://github.com/elixir-lang/elixir/issues/13001

**Comment by AHBruns** [comment]
I couldn't make a reliable reproduction in a smaller app. It *sometimes* happened, but seemingly randomly.

**Comment by lud-wj** [comment]
I had the same issue until I put my configuration directly in the code to avoir it.

On my machine is was systematical, but not on the first compilation.

So basically if I run `rm -rf .elixir_ls` and restart vscode, everything is fine. Then if I change any module, the error shows.

**Comment by lukaszsamson** [comment]
@lud-wj please create a repro

**Comment by lud-wj** [comment]
I am not reproducing. I reverted my change in my real codebase to see if that pops up again.
